### ISSUE TITLE
username undefined error

### ISSUE THREAD

**Issue by tzarebczan** [Crowndev/Twitter-Tip#1]
Hey Crowndev, are you still maintaining this tipbot? I set it up as a quick test and ran into this:

Any reason why we shouldn't use this tipbot if we can make it work with some fixes to the Twitter API? 

```
info:    Connected TipBot to Twitter.
/home/ubuntu/Twitter-Tip/twitter.js:60
    if (from == settings.twtter.username.toLowerCase())
                               ^

TypeError: Cannot read property 'username' of undefined
    at null.<anonymous> (/home/ubuntu/Twitter-Tip/twitter.js:60:32)
    at emitOne (events.js:77:13)
    at emit (events.js:169:7)
    at null.<anonymous> (/home/ubuntu/Twitter-Tip/node_modules/twit/lib/streaming-api-connection.js:294:56)
    at emitOne (events.js:77:13)
    at emit (events.js:169:7)
    at Parser.parse (/home/ubuntu/Twitter-Tip/node_modules/twit/lib/parser.js:41:16)
    at IncomingMessage.<anonymous> (/home/ubuntu/Twitter-Tip/node_modules/twit/lib/streaming-api-connection.js:115:19)
    at emitOne (events.js:82:20)
    at IncomingMessage.emit (events.js:169:7)

```

**Comment by tzarebczan** [comment]
Looks like typos of Twitter in the source, fixing and trying again. 

Does the tipbot only reply to tweets or can DMs be used?

**Comment by hypermoist** [comment]
I'm hopeful this comes through but it's only via tweets

**Comment by tzarebczan** [comment]
@Extrememist thanks for the reply. I got it up and running after the typo fix, but the bot doesn't seem to pick up any activity when I tweet at it. Any idea what might be wrong? 

Is this your project? Can you recommend any other open source Tipbots for Twitter if it won't be actively developed?

**Comment by hypermoist** [comment]
I'm apart of the project. Your Twitter account isn't private is it

**Comment by tzarebczan** [comment]
@Extrememist nope, not private: https://twitter.com/@LBC_TipBot

I think I have the API keys setup correctly. It did seem to read the first message because I ran into the syntax issue. I see "info:    Connected TipBot to Twitter." in my log, that's all. 

Are the commands !help, or just help? Part of the code has: `status: "@" + from + " Here is a list of commands: !balance !send !tip !withdraw !address`

Also, Twitter prevents me from sending additonal messages with the same text( i.e. tweeting at the tipbot with the help message). This is where DM support might be useful.

**Comment by hypermoist** [comment]
I don't know as that hasn't been used for ages haha so it might be out of
date with twitters api

**Comment by rraallvv** [comment]
@tzarebczan Mine does pick the bot activity, but [this line](https://github.com/Crowndev/Twitter-Tip/blob/master/twitter.js#L60) in particular was preventing the bot from responding to its own tweets. In my case I was trying the commands from the bot account itself.

@Extrememist do you know if passing `from` as a parameter when [asking for a new address account](https://github.com/Crowndev/Twitter-Tip/blob/master/twitter.js#L125) is a feature of the coin RPC API? Like a seed or something? Because I can't find a way to associate each twitter account to its generated address, at least not with the Nimiq blockchain, instead I'll have to use a database for the association.
